//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttLogs.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx", ConfigurationName="ServiceReference1.AttendanceServiceSoap")]
    public interface AttendanceServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ac3.alchavo.com/AttendanceService.asmx/ImportBioPunchs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AttLogs.ServiceReference1.ImportInfo ImportBioPunchs(string CompanyIdentification, string UserIdentification, System.Data.DataTable UploadTable);
        
        // CODEGEN: Parameter 'FileToImport' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ac3.alchavo.com/AttendanceService.asmx/ImportHours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AttLogs.ServiceReference1.ImportHoursResponse ImportHours(AttLogs.ServiceReference1.ImportHoursRequest request);
        
        // CODEGEN: Parameter 'FileToImport' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ac3.alchavo.com/AttendanceService.asmx/ImportSchedules", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AttLogs.ServiceReference1.ImportSchedulesResponse ImportSchedules(AttLogs.ServiceReference1.ImportSchedulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ac3.alchavo.com/AttendanceService.asmx/AddPunch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AttLogs.ServiceReference1.PunchInfo AddPunch(string CompanyIdentification, string UserIdentification, string EmployeeID, string DepartmentID, System.DateTime PunchTime, bool IsPunchIn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class ImportInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private RejectedRecord[] rejectedLinesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RejectedRecord[] RejectedLines {
            get {
                return this.rejectedLinesField;
            }
            set {
                this.rejectedLinesField = value;
                this.RaisePropertyChanged("RejectedLines");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class RejectedRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string employeeIdentField;
        
        private string departmentIdentField;
        
        private string punchInDateTimeField;
        
        private string punchOutDateTimeField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmployeeIdent {
            get {
                return this.employeeIdentField;
            }
            set {
                this.employeeIdentField = value;
                this.RaisePropertyChanged("EmployeeIdent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DepartmentIdent {
            get {
                return this.departmentIdentField;
            }
            set {
                this.departmentIdentField = value;
                this.RaisePropertyChanged("DepartmentIdent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PunchInDateTime {
            get {
                return this.punchInDateTimeField;
            }
            set {
                this.punchInDateTimeField = value;
                this.RaisePropertyChanged("PunchInDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PunchOutDateTime {
            get {
                return this.punchOutDateTimeField;
            }
            set {
                this.punchOutDateTimeField = value;
                this.RaisePropertyChanged("PunchOutDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class RejectedPunch : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string employeeIdentField;
        
        private string departmentIdentField;
        
        private string punchTimeField;
        
        private string isPunchInField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmployeeIdent {
            get {
                return this.employeeIdentField;
            }
            set {
                this.employeeIdentField = value;
                this.RaisePropertyChanged("EmployeeIdent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DepartmentIdent {
            get {
                return this.departmentIdentField;
            }
            set {
                this.departmentIdentField = value;
                this.RaisePropertyChanged("DepartmentIdent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PunchTime {
            get {
                return this.punchTimeField;
            }
            set {
                this.punchTimeField = value;
                this.RaisePropertyChanged("PunchTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IsPunchIn {
            get {
                return this.isPunchInField;
            }
            set {
                this.isPunchInField = value;
                this.RaisePropertyChanged("IsPunchIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class PunchInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private RejectedPunch[] rejectedLinesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RejectedPunch[] RejectedLines {
            get {
                return this.rejectedLinesField;
            }
            set {
                this.rejectedLinesField = value;
                this.RaisePropertyChanged("RejectedLines");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class RejectedSchedules : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string employeeIdentField;
        
        private string bidPeriodStartField;
        
        private string bidPeriodEndField;
        
        private string sundayFirstPunchInTimeField;
        
        private string sundayFirstPunchOutTimeField;
        
        private string sundaySecondPunchInTimeField;
        
        private string sundaySecondPunchOutTimeField;
        
        private string mondayFirstPunchInTimeField;
        
        private string mondayFirstPunchOutTimeField;
        
        private string mondaySecondPunchInTimeField;
        
        private string mondaySecondPunchOutTimeField;
        
        private string tuesdayFirstPunchInTimeField;
        
        private string tuesdayFirstPunchOutTimeField;
        
        private string tuesdaySecondPunchInTimeField;
        
        private string tuesdaySecondPunchOutTimeField;
        
        private string wednesdayFirstPunchInTimeField;
        
        private string wednesdayFirstPunchOutTimeField;
        
        private string wednesdaySecondPunchInTimeField;
        
        private string wednesdaySecondPunchOutTimeField;
        
        private string thursdayFirstPunchInTimeField;
        
        private string thursdayFirstPunchOutTimeField;
        
        private string thursdaySecondPunchInTimeField;
        
        private string thursdaySecondPunchOutTimeField;
        
        private string fridayFirstPunchInTimeField;
        
        private string fridayFirstPunchOutTimeField;
        
        private string fridaySecondPunchInTimeField;
        
        private string fridaySecondPunchOutTimeField;
        
        private string saturdayFirstPunchInTimeField;
        
        private string saturdayFirstPunchOutTimeField;
        
        private string saturdaySecondPunchInTimeField;
        
        private string saturdaySecondPunchOutTimeField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmployeeIdent {
            get {
                return this.employeeIdentField;
            }
            set {
                this.employeeIdentField = value;
                this.RaisePropertyChanged("EmployeeIdent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BidPeriodStart {
            get {
                return this.bidPeriodStartField;
            }
            set {
                this.bidPeriodStartField = value;
                this.RaisePropertyChanged("BidPeriodStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BidPeriodEnd {
            get {
                return this.bidPeriodEndField;
            }
            set {
                this.bidPeriodEndField = value;
                this.RaisePropertyChanged("BidPeriodEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SundayFirstPunchInTime {
            get {
                return this.sundayFirstPunchInTimeField;
            }
            set {
                this.sundayFirstPunchInTimeField = value;
                this.RaisePropertyChanged("SundayFirstPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SundayFirstPunchOutTime {
            get {
                return this.sundayFirstPunchOutTimeField;
            }
            set {
                this.sundayFirstPunchOutTimeField = value;
                this.RaisePropertyChanged("SundayFirstPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SundaySecondPunchInTime {
            get {
                return this.sundaySecondPunchInTimeField;
            }
            set {
                this.sundaySecondPunchInTimeField = value;
                this.RaisePropertyChanged("SundaySecondPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SundaySecondPunchOutTime {
            get {
                return this.sundaySecondPunchOutTimeField;
            }
            set {
                this.sundaySecondPunchOutTimeField = value;
                this.RaisePropertyChanged("SundaySecondPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MondayFirstPunchInTime {
            get {
                return this.mondayFirstPunchInTimeField;
            }
            set {
                this.mondayFirstPunchInTimeField = value;
                this.RaisePropertyChanged("MondayFirstPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MondayFirstPunchOutTime {
            get {
                return this.mondayFirstPunchOutTimeField;
            }
            set {
                this.mondayFirstPunchOutTimeField = value;
                this.RaisePropertyChanged("MondayFirstPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MondaySecondPunchInTime {
            get {
                return this.mondaySecondPunchInTimeField;
            }
            set {
                this.mondaySecondPunchInTimeField = value;
                this.RaisePropertyChanged("MondaySecondPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MondaySecondPunchOutTime {
            get {
                return this.mondaySecondPunchOutTimeField;
            }
            set {
                this.mondaySecondPunchOutTimeField = value;
                this.RaisePropertyChanged("MondaySecondPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TuesdayFirstPunchInTime {
            get {
                return this.tuesdayFirstPunchInTimeField;
            }
            set {
                this.tuesdayFirstPunchInTimeField = value;
                this.RaisePropertyChanged("TuesdayFirstPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TuesdayFirstPunchOutTime {
            get {
                return this.tuesdayFirstPunchOutTimeField;
            }
            set {
                this.tuesdayFirstPunchOutTimeField = value;
                this.RaisePropertyChanged("TuesdayFirstPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TuesdaySecondPunchInTime {
            get {
                return this.tuesdaySecondPunchInTimeField;
            }
            set {
                this.tuesdaySecondPunchInTimeField = value;
                this.RaisePropertyChanged("TuesdaySecondPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TuesdaySecondPunchOutTime {
            get {
                return this.tuesdaySecondPunchOutTimeField;
            }
            set {
                this.tuesdaySecondPunchOutTimeField = value;
                this.RaisePropertyChanged("TuesdaySecondPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string WednesdayFirstPunchInTime {
            get {
                return this.wednesdayFirstPunchInTimeField;
            }
            set {
                this.wednesdayFirstPunchInTimeField = value;
                this.RaisePropertyChanged("WednesdayFirstPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string WednesdayFirstPunchOutTime {
            get {
                return this.wednesdayFirstPunchOutTimeField;
            }
            set {
                this.wednesdayFirstPunchOutTimeField = value;
                this.RaisePropertyChanged("WednesdayFirstPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string WednesdaySecondPunchInTime {
            get {
                return this.wednesdaySecondPunchInTimeField;
            }
            set {
                this.wednesdaySecondPunchInTimeField = value;
                this.RaisePropertyChanged("WednesdaySecondPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string WednesdaySecondPunchOutTime {
            get {
                return this.wednesdaySecondPunchOutTimeField;
            }
            set {
                this.wednesdaySecondPunchOutTimeField = value;
                this.RaisePropertyChanged("WednesdaySecondPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ThursdayFirstPunchInTime {
            get {
                return this.thursdayFirstPunchInTimeField;
            }
            set {
                this.thursdayFirstPunchInTimeField = value;
                this.RaisePropertyChanged("ThursdayFirstPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ThursdayFirstPunchOutTime {
            get {
                return this.thursdayFirstPunchOutTimeField;
            }
            set {
                this.thursdayFirstPunchOutTimeField = value;
                this.RaisePropertyChanged("ThursdayFirstPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ThursdaySecondPunchInTime {
            get {
                return this.thursdaySecondPunchInTimeField;
            }
            set {
                this.thursdaySecondPunchInTimeField = value;
                this.RaisePropertyChanged("ThursdaySecondPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ThursdaySecondPunchOutTime {
            get {
                return this.thursdaySecondPunchOutTimeField;
            }
            set {
                this.thursdaySecondPunchOutTimeField = value;
                this.RaisePropertyChanged("ThursdaySecondPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string FridayFirstPunchInTime {
            get {
                return this.fridayFirstPunchInTimeField;
            }
            set {
                this.fridayFirstPunchInTimeField = value;
                this.RaisePropertyChanged("FridayFirstPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string FridayFirstPunchOutTime {
            get {
                return this.fridayFirstPunchOutTimeField;
            }
            set {
                this.fridayFirstPunchOutTimeField = value;
                this.RaisePropertyChanged("FridayFirstPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string FridaySecondPunchInTime {
            get {
                return this.fridaySecondPunchInTimeField;
            }
            set {
                this.fridaySecondPunchInTimeField = value;
                this.RaisePropertyChanged("FridaySecondPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string FridaySecondPunchOutTime {
            get {
                return this.fridaySecondPunchOutTimeField;
            }
            set {
                this.fridaySecondPunchOutTimeField = value;
                this.RaisePropertyChanged("FridaySecondPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string SaturdayFirstPunchInTime {
            get {
                return this.saturdayFirstPunchInTimeField;
            }
            set {
                this.saturdayFirstPunchInTimeField = value;
                this.RaisePropertyChanged("SaturdayFirstPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string SaturdayFirstPunchOutTime {
            get {
                return this.saturdayFirstPunchOutTimeField;
            }
            set {
                this.saturdayFirstPunchOutTimeField = value;
                this.RaisePropertyChanged("SaturdayFirstPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string SaturdaySecondPunchInTime {
            get {
                return this.saturdaySecondPunchInTimeField;
            }
            set {
                this.saturdaySecondPunchInTimeField = value;
                this.RaisePropertyChanged("SaturdaySecondPunchInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string SaturdaySecondPunchOutTime {
            get {
                return this.saturdaySecondPunchOutTimeField;
            }
            set {
                this.saturdaySecondPunchOutTimeField = value;
                this.RaisePropertyChanged("SaturdaySecondPunchOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class ImportedSchedulesInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private RejectedSchedules[] rejectedLinesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RejectedSchedules[] RejectedLines {
            get {
                return this.rejectedLinesField;
            }
            set {
                this.rejectedLinesField = value;
                this.RaisePropertyChanged("RejectedLines");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportHours", WrapperNamespace="http://ac3.alchavo.com/AttendanceService.asmx", IsWrapped=true)]
    public partial class ImportHoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx", Order=0)]
        public string CompanyIdentification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx", Order=1)]
        public string UserIdentification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileToImport;
        
        public ImportHoursRequest() {
        }
        
        public ImportHoursRequest(string CompanyIdentification, string UserIdentification, byte[] FileToImport) {
            this.CompanyIdentification = CompanyIdentification;
            this.UserIdentification = UserIdentification;
            this.FileToImport = FileToImport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportHoursResponse", WrapperNamespace="http://ac3.alchavo.com/AttendanceService.asmx", IsWrapped=true)]
    public partial class ImportHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx", Order=0)]
        public AttLogs.ServiceReference1.ImportInfo ImportHoursResult;
        
        public ImportHoursResponse() {
        }
        
        public ImportHoursResponse(AttLogs.ServiceReference1.ImportInfo ImportHoursResult) {
            this.ImportHoursResult = ImportHoursResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportSchedules", WrapperNamespace="http://ac3.alchavo.com/AttendanceService.asmx", IsWrapped=true)]
    public partial class ImportSchedulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx", Order=0)]
        public string CompanyIdentification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx", Order=1)]
        public string UserIdentification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileToImport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx", Order=3)]
        public bool OverwritePrevious;
        
        public ImportSchedulesRequest() {
        }
        
        public ImportSchedulesRequest(string CompanyIdentification, string UserIdentification, byte[] FileToImport, bool OverwritePrevious) {
            this.CompanyIdentification = CompanyIdentification;
            this.UserIdentification = UserIdentification;
            this.FileToImport = FileToImport;
            this.OverwritePrevious = OverwritePrevious;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportSchedulesResponse", WrapperNamespace="http://ac3.alchavo.com/AttendanceService.asmx", IsWrapped=true)]
    public partial class ImportSchedulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx", Order=0)]
        public AttLogs.ServiceReference1.ImportedSchedulesInfo ImportSchedulesResult;
        
        public ImportSchedulesResponse() {
        }
        
        public ImportSchedulesResponse(AttLogs.ServiceReference1.ImportedSchedulesInfo ImportSchedulesResult) {
            this.ImportSchedulesResult = ImportSchedulesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AttendanceServiceSoapChannel : AttLogs.ServiceReference1.AttendanceServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttendanceServiceSoapClient : System.ServiceModel.ClientBase<AttLogs.ServiceReference1.AttendanceServiceSoap>, AttLogs.ServiceReference1.AttendanceServiceSoap {
        
        public AttendanceServiceSoapClient() {
        }
        
        public AttendanceServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AttendanceServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttendanceServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttendanceServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AttLogs.ServiceReference1.ImportInfo ImportBioPunchs(string CompanyIdentification, string UserIdentification, System.Data.DataTable UploadTable) {
            return base.Channel.ImportBioPunchs(CompanyIdentification, UserIdentification, UploadTable);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AttLogs.ServiceReference1.ImportHoursResponse AttLogs.ServiceReference1.AttendanceServiceSoap.ImportHours(AttLogs.ServiceReference1.ImportHoursRequest request) {
            return base.Channel.ImportHours(request);
        }
        
        public AttLogs.ServiceReference1.ImportInfo ImportHours(string CompanyIdentification, string UserIdentification, byte[] FileToImport) {
            AttLogs.ServiceReference1.ImportHoursRequest inValue = new AttLogs.ServiceReference1.ImportHoursRequest();
            inValue.CompanyIdentification = CompanyIdentification;
            inValue.UserIdentification = UserIdentification;
            inValue.FileToImport = FileToImport;
            AttLogs.ServiceReference1.ImportHoursResponse retVal = ((AttLogs.ServiceReference1.AttendanceServiceSoap)(this)).ImportHours(inValue);
            return retVal.ImportHoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AttLogs.ServiceReference1.ImportSchedulesResponse AttLogs.ServiceReference1.AttendanceServiceSoap.ImportSchedules(AttLogs.ServiceReference1.ImportSchedulesRequest request) {
            return base.Channel.ImportSchedules(request);
        }
        
        public AttLogs.ServiceReference1.ImportedSchedulesInfo ImportSchedules(string CompanyIdentification, string UserIdentification, byte[] FileToImport, bool OverwritePrevious) {
            AttLogs.ServiceReference1.ImportSchedulesRequest inValue = new AttLogs.ServiceReference1.ImportSchedulesRequest();
            inValue.CompanyIdentification = CompanyIdentification;
            inValue.UserIdentification = UserIdentification;
            inValue.FileToImport = FileToImport;
            inValue.OverwritePrevious = OverwritePrevious;
            AttLogs.ServiceReference1.ImportSchedulesResponse retVal = ((AttLogs.ServiceReference1.AttendanceServiceSoap)(this)).ImportSchedules(inValue);
            return retVal.ImportSchedulesResult;
        }
        
        public AttLogs.ServiceReference1.PunchInfo AddPunch(string CompanyIdentification, string UserIdentification, string EmployeeID, string DepartmentID, System.DateTime PunchTime, bool IsPunchIn) {
            return base.Channel.AddPunch(CompanyIdentification, UserIdentification, EmployeeID, DepartmentID, PunchTime, IsPunchIn);
        }
    }
}
