//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AttLogs.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AttendanceServiceSoap", Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class AttendanceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ImportBioPunchsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportHoursOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportSchedulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPunchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AttendanceService() {
            this.Url = global::AttLogs.Properties.Settings.Default.AttLogs_localhost_AttendanceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ImportBioPunchsCompletedEventHandler ImportBioPunchsCompleted;
        
        /// <remarks/>
        public event ImportHoursCompletedEventHandler ImportHoursCompleted;
        
        /// <remarks/>
        public event ImportSchedulesCompletedEventHandler ImportSchedulesCompleted;
        
        /// <remarks/>
        public event AddPunchCompletedEventHandler AddPunchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ac3.alchavo.com/AttendanceService.asmx/ImportBioPunchs", RequestNamespace="http://ac3.alchavo.com/AttendanceService.asmx", ResponseNamespace="http://ac3.alchavo.com/AttendanceService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ImportInfo ImportBioPunchs(string CompanyIdentification, string UserIdentification, System.Data.DataTable UploadTable) {
            object[] results = this.Invoke("ImportBioPunchs", new object[] {
                        CompanyIdentification,
                        UserIdentification,
                        UploadTable});
            return ((ImportInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ImportBioPunchsAsync(string CompanyIdentification, string UserIdentification, System.Data.DataTable UploadTable) {
            this.ImportBioPunchsAsync(CompanyIdentification, UserIdentification, UploadTable, null);
        }
        
        /// <remarks/>
        public void ImportBioPunchsAsync(string CompanyIdentification, string UserIdentification, System.Data.DataTable UploadTable, object userState) {
            if ((this.ImportBioPunchsOperationCompleted == null)) {
                this.ImportBioPunchsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportBioPunchsOperationCompleted);
            }
            this.InvokeAsync("ImportBioPunchs", new object[] {
                        CompanyIdentification,
                        UserIdentification,
                        UploadTable}, this.ImportBioPunchsOperationCompleted, userState);
        }
        
        private void OnImportBioPunchsOperationCompleted(object arg) {
            if ((this.ImportBioPunchsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportBioPunchsCompleted(this, new ImportBioPunchsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ac3.alchavo.com/AttendanceService.asmx/ImportHours", RequestNamespace="http://ac3.alchavo.com/AttendanceService.asmx", ResponseNamespace="http://ac3.alchavo.com/AttendanceService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ImportInfo ImportHours(string CompanyIdentification, string UserIdentification, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] FileToImport) {
            object[] results = this.Invoke("ImportHours", new object[] {
                        CompanyIdentification,
                        UserIdentification,
                        FileToImport});
            return ((ImportInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ImportHoursAsync(string CompanyIdentification, string UserIdentification, byte[] FileToImport) {
            this.ImportHoursAsync(CompanyIdentification, UserIdentification, FileToImport, null);
        }
        
        /// <remarks/>
        public void ImportHoursAsync(string CompanyIdentification, string UserIdentification, byte[] FileToImport, object userState) {
            if ((this.ImportHoursOperationCompleted == null)) {
                this.ImportHoursOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportHoursOperationCompleted);
            }
            this.InvokeAsync("ImportHours", new object[] {
                        CompanyIdentification,
                        UserIdentification,
                        FileToImport}, this.ImportHoursOperationCompleted, userState);
        }
        
        private void OnImportHoursOperationCompleted(object arg) {
            if ((this.ImportHoursCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportHoursCompleted(this, new ImportHoursCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ac3.alchavo.com/AttendanceService.asmx/ImportSchedules", RequestNamespace="http://ac3.alchavo.com/AttendanceService.asmx", ResponseNamespace="http://ac3.alchavo.com/AttendanceService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ImportedSchedulesInfo ImportSchedules(string CompanyIdentification, string UserIdentification, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] FileToImport, bool OverwritePrevious) {
            object[] results = this.Invoke("ImportSchedules", new object[] {
                        CompanyIdentification,
                        UserIdentification,
                        FileToImport,
                        OverwritePrevious});
            return ((ImportedSchedulesInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ImportSchedulesAsync(string CompanyIdentification, string UserIdentification, byte[] FileToImport, bool OverwritePrevious) {
            this.ImportSchedulesAsync(CompanyIdentification, UserIdentification, FileToImport, OverwritePrevious, null);
        }
        
        /// <remarks/>
        public void ImportSchedulesAsync(string CompanyIdentification, string UserIdentification, byte[] FileToImport, bool OverwritePrevious, object userState) {
            if ((this.ImportSchedulesOperationCompleted == null)) {
                this.ImportSchedulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportSchedulesOperationCompleted);
            }
            this.InvokeAsync("ImportSchedules", new object[] {
                        CompanyIdentification,
                        UserIdentification,
                        FileToImport,
                        OverwritePrevious}, this.ImportSchedulesOperationCompleted, userState);
        }
        
        private void OnImportSchedulesOperationCompleted(object arg) {
            if ((this.ImportSchedulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportSchedulesCompleted(this, new ImportSchedulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ac3.alchavo.com/AttendanceService.asmx/AddPunch", RequestNamespace="http://ac3.alchavo.com/AttendanceService.asmx", ResponseNamespace="http://ac3.alchavo.com/AttendanceService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PunchInfo AddPunch(string CompanyIdentification, string UserIdentification, string EmployeeID, string DepartmentID, System.DateTime PunchTime, bool IsPunchIn) {
            object[] results = this.Invoke("AddPunch", new object[] {
                        CompanyIdentification,
                        UserIdentification,
                        EmployeeID,
                        DepartmentID,
                        PunchTime,
                        IsPunchIn});
            return ((PunchInfo)(results[0]));
        }
        
        /// <remarks/>
        public void AddPunchAsync(string CompanyIdentification, string UserIdentification, string EmployeeID, string DepartmentID, System.DateTime PunchTime, bool IsPunchIn) {
            this.AddPunchAsync(CompanyIdentification, UserIdentification, EmployeeID, DepartmentID, PunchTime, IsPunchIn, null);
        }
        
        /// <remarks/>
        public void AddPunchAsync(string CompanyIdentification, string UserIdentification, string EmployeeID, string DepartmentID, System.DateTime PunchTime, bool IsPunchIn, object userState) {
            if ((this.AddPunchOperationCompleted == null)) {
                this.AddPunchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPunchOperationCompleted);
            }
            this.InvokeAsync("AddPunch", new object[] {
                        CompanyIdentification,
                        UserIdentification,
                        EmployeeID,
                        DepartmentID,
                        PunchTime,
                        IsPunchIn}, this.AddPunchOperationCompleted, userState);
        }
        
        private void OnAddPunchOperationCompleted(object arg) {
            if ((this.AddPunchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPunchCompleted(this, new AddPunchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class ImportInfo {
        
        private string statusField;
        
        private RejectedRecord[] rejectedLinesField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RejectedRecord[] RejectedLines {
            get {
                return this.rejectedLinesField;
            }
            set {
                this.rejectedLinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class RejectedRecord {
        
        private string employeeIdentField;
        
        private string departmentIdentField;
        
        private string punchInDateTimeField;
        
        private string punchOutDateTimeField;
        
        private string reasonField;
        
        /// <remarks/>
        public string EmployeeIdent {
            get {
                return this.employeeIdentField;
            }
            set {
                this.employeeIdentField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentIdent {
            get {
                return this.departmentIdentField;
            }
            set {
                this.departmentIdentField = value;
            }
        }
        
        /// <remarks/>
        public string PunchInDateTime {
            get {
                return this.punchInDateTimeField;
            }
            set {
                this.punchInDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string PunchOutDateTime {
            get {
                return this.punchOutDateTimeField;
            }
            set {
                this.punchOutDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class RejectedPunch {
        
        private string employeeIdentField;
        
        private string departmentIdentField;
        
        private string punchTimeField;
        
        private string isPunchInField;
        
        private string reasonField;
        
        /// <remarks/>
        public string EmployeeIdent {
            get {
                return this.employeeIdentField;
            }
            set {
                this.employeeIdentField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentIdent {
            get {
                return this.departmentIdentField;
            }
            set {
                this.departmentIdentField = value;
            }
        }
        
        /// <remarks/>
        public string PunchTime {
            get {
                return this.punchTimeField;
            }
            set {
                this.punchTimeField = value;
            }
        }
        
        /// <remarks/>
        public string IsPunchIn {
            get {
                return this.isPunchInField;
            }
            set {
                this.isPunchInField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class PunchInfo {
        
        private string statusField;
        
        private RejectedPunch[] rejectedLinesField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RejectedPunch[] RejectedLines {
            get {
                return this.rejectedLinesField;
            }
            set {
                this.rejectedLinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class RejectedSchedules {
        
        private string employeeIdentField;
        
        private string bidPeriodStartField;
        
        private string bidPeriodEndField;
        
        private string sundayFirstPunchInTimeField;
        
        private string sundayFirstPunchOutTimeField;
        
        private string sundaySecondPunchInTimeField;
        
        private string sundaySecondPunchOutTimeField;
        
        private string mondayFirstPunchInTimeField;
        
        private string mondayFirstPunchOutTimeField;
        
        private string mondaySecondPunchInTimeField;
        
        private string mondaySecondPunchOutTimeField;
        
        private string tuesdayFirstPunchInTimeField;
        
        private string tuesdayFirstPunchOutTimeField;
        
        private string tuesdaySecondPunchInTimeField;
        
        private string tuesdaySecondPunchOutTimeField;
        
        private string wednesdayFirstPunchInTimeField;
        
        private string wednesdayFirstPunchOutTimeField;
        
        private string wednesdaySecondPunchInTimeField;
        
        private string wednesdaySecondPunchOutTimeField;
        
        private string thursdayFirstPunchInTimeField;
        
        private string thursdayFirstPunchOutTimeField;
        
        private string thursdaySecondPunchInTimeField;
        
        private string thursdaySecondPunchOutTimeField;
        
        private string fridayFirstPunchInTimeField;
        
        private string fridayFirstPunchOutTimeField;
        
        private string fridaySecondPunchInTimeField;
        
        private string fridaySecondPunchOutTimeField;
        
        private string saturdayFirstPunchInTimeField;
        
        private string saturdayFirstPunchOutTimeField;
        
        private string saturdaySecondPunchInTimeField;
        
        private string saturdaySecondPunchOutTimeField;
        
        private string reasonField;
        
        /// <remarks/>
        public string EmployeeIdent {
            get {
                return this.employeeIdentField;
            }
            set {
                this.employeeIdentField = value;
            }
        }
        
        /// <remarks/>
        public string BidPeriodStart {
            get {
                return this.bidPeriodStartField;
            }
            set {
                this.bidPeriodStartField = value;
            }
        }
        
        /// <remarks/>
        public string BidPeriodEnd {
            get {
                return this.bidPeriodEndField;
            }
            set {
                this.bidPeriodEndField = value;
            }
        }
        
        /// <remarks/>
        public string SundayFirstPunchInTime {
            get {
                return this.sundayFirstPunchInTimeField;
            }
            set {
                this.sundayFirstPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SundayFirstPunchOutTime {
            get {
                return this.sundayFirstPunchOutTimeField;
            }
            set {
                this.sundayFirstPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SundaySecondPunchInTime {
            get {
                return this.sundaySecondPunchInTimeField;
            }
            set {
                this.sundaySecondPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SundaySecondPunchOutTime {
            get {
                return this.sundaySecondPunchOutTimeField;
            }
            set {
                this.sundaySecondPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string MondayFirstPunchInTime {
            get {
                return this.mondayFirstPunchInTimeField;
            }
            set {
                this.mondayFirstPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string MondayFirstPunchOutTime {
            get {
                return this.mondayFirstPunchOutTimeField;
            }
            set {
                this.mondayFirstPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string MondaySecondPunchInTime {
            get {
                return this.mondaySecondPunchInTimeField;
            }
            set {
                this.mondaySecondPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string MondaySecondPunchOutTime {
            get {
                return this.mondaySecondPunchOutTimeField;
            }
            set {
                this.mondaySecondPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string TuesdayFirstPunchInTime {
            get {
                return this.tuesdayFirstPunchInTimeField;
            }
            set {
                this.tuesdayFirstPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string TuesdayFirstPunchOutTime {
            get {
                return this.tuesdayFirstPunchOutTimeField;
            }
            set {
                this.tuesdayFirstPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string TuesdaySecondPunchInTime {
            get {
                return this.tuesdaySecondPunchInTimeField;
            }
            set {
                this.tuesdaySecondPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string TuesdaySecondPunchOutTime {
            get {
                return this.tuesdaySecondPunchOutTimeField;
            }
            set {
                this.tuesdaySecondPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string WednesdayFirstPunchInTime {
            get {
                return this.wednesdayFirstPunchInTimeField;
            }
            set {
                this.wednesdayFirstPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string WednesdayFirstPunchOutTime {
            get {
                return this.wednesdayFirstPunchOutTimeField;
            }
            set {
                this.wednesdayFirstPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string WednesdaySecondPunchInTime {
            get {
                return this.wednesdaySecondPunchInTimeField;
            }
            set {
                this.wednesdaySecondPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string WednesdaySecondPunchOutTime {
            get {
                return this.wednesdaySecondPunchOutTimeField;
            }
            set {
                this.wednesdaySecondPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ThursdayFirstPunchInTime {
            get {
                return this.thursdayFirstPunchInTimeField;
            }
            set {
                this.thursdayFirstPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ThursdayFirstPunchOutTime {
            get {
                return this.thursdayFirstPunchOutTimeField;
            }
            set {
                this.thursdayFirstPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ThursdaySecondPunchInTime {
            get {
                return this.thursdaySecondPunchInTimeField;
            }
            set {
                this.thursdaySecondPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ThursdaySecondPunchOutTime {
            get {
                return this.thursdaySecondPunchOutTimeField;
            }
            set {
                this.thursdaySecondPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string FridayFirstPunchInTime {
            get {
                return this.fridayFirstPunchInTimeField;
            }
            set {
                this.fridayFirstPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string FridayFirstPunchOutTime {
            get {
                return this.fridayFirstPunchOutTimeField;
            }
            set {
                this.fridayFirstPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string FridaySecondPunchInTime {
            get {
                return this.fridaySecondPunchInTimeField;
            }
            set {
                this.fridaySecondPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string FridaySecondPunchOutTime {
            get {
                return this.fridaySecondPunchOutTimeField;
            }
            set {
                this.fridaySecondPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SaturdayFirstPunchInTime {
            get {
                return this.saturdayFirstPunchInTimeField;
            }
            set {
                this.saturdayFirstPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SaturdayFirstPunchOutTime {
            get {
                return this.saturdayFirstPunchOutTimeField;
            }
            set {
                this.saturdayFirstPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SaturdaySecondPunchInTime {
            get {
                return this.saturdaySecondPunchInTimeField;
            }
            set {
                this.saturdaySecondPunchInTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SaturdaySecondPunchOutTime {
            get {
                return this.saturdaySecondPunchOutTimeField;
            }
            set {
                this.saturdaySecondPunchOutTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ac3.alchavo.com/AttendanceService.asmx")]
    public partial class ImportedSchedulesInfo {
        
        private string statusField;
        
        private RejectedSchedules[] rejectedLinesField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RejectedSchedules[] RejectedLines {
            get {
                return this.rejectedLinesField;
            }
            set {
                this.rejectedLinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ImportBioPunchsCompletedEventHandler(object sender, ImportBioPunchsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportBioPunchsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportBioPunchsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ImportInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ImportInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ImportHoursCompletedEventHandler(object sender, ImportHoursCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportHoursCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportHoursCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ImportInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ImportInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ImportSchedulesCompletedEventHandler(object sender, ImportSchedulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportSchedulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportSchedulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ImportedSchedulesInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ImportedSchedulesInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddPunchCompletedEventHandler(object sender, AddPunchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPunchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPunchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PunchInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PunchInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591